# Generated by Django 5.2 on 2025-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='valuation',
            field=models.CharField(blank=True, choices=[('Undervalued', 'Undervalued'), ('Fairly valued', 'Fairly valued'), ('Overvalued', 'Overvalued')], max_length=20, null=True),
        ),
    ]
