# Generated by Django 5.2 on 2025-07-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_capital_expenditures_stock_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='valuation_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
