# Generated by Django 5.2 on 2025-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_risk_score_stock_valuation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dcf_intrinsic_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
