# Generated by Django 5.2 on 2025-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_dcf_intrinsic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
