# Generated by Django 5.2 on 2025-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_previous_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='predicted_closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
