# Generated by Django 5.2 on 2025-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_predicted_closing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expected_percentage_change_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
