# Generated by Django 5.2 on 2025-07-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationsdatabase',
            table='notifications',
        ),
    ]
