# Generated by Django 5.2 on 2025-06-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdatabase',
            options={'managed': False},
        ),
    ]
