# Generated by Django 5.2 on 2025-06-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0002_alter_accountdatabase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdatabase',
            options={},
        ),
    ]
