# Generated by Django 5.2 on 2025-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0003_alter_accountdatabase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatabase',
            name='alert_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='accountdatabase',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='accountdatabase',
            name='risk_tolerance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
