# Generated by Django 5.2 on 2025-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0004_accountdatabase_alert_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatabase',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='accountdatabase',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
