# Generated by Django 5.2 on 2025-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0005_alter_accountdatabase_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatabase',
            name='is_oauth_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountdatabase',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accountdatabase',
            name='oauth_provider_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
