# Generated by Django 5.2 on 2025-07-27 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0006_accountdatabase_is_oauth_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatabase',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountdatabase',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
