# Generated by Django 5.2 on 2025-07-27 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeraccountapp', '0007_accountdatabase_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatabase',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
